export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_IN_CART = 'GET_PRODUCTS_IN_CART';
export const PLUS_PRODUCT = 'PLUS_PRODUCT';
export const MINUS_PRODUCT = 'MINUS_PRODUCT';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
